apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ephemeral-base

images:
  - name: registry.toolz.homelabz.eu/library/cks-terminal-mgmt
    newTag: 10e8b3b4f9547757ca1f98cb897b16e2bddc49c1

patches:
  - target:
      kind: Ingress
      name: cks-terminal-mgmt
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: terminal.toolz.cks.homelabz.eu
      - op: replace
        path: /spec/tls/0/hosts/0
        value: terminal.toolz.cks.homelabz.eu
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: terminal.toolz.cks.homelabz.eu
      - op: replace
        path: /spec/ingressClassName
        value: nginx

configMapGenerator:
  - name: cks-terminal-mgmt-config
    behavior: merge
    envs:
      - configmap
