apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../ephemeral-base

images:
  - name: registry.homelabz.eu/library/cks-terminal-mgmt
    newTag: 3c2de13244a9d74e747e69493f9e53177351fba2

patches:
  - target:
      kind: Ingress
      name: cks-terminal-mgmt
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: terminal.toolz.homelabz.eu
      - op: replace
        path: /spec/tls/0/hosts/0
        value: terminal.toolz.homelabz.eu
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: terminal.toolz.homelabz.eu
      - op: replace
        path: /spec/ingressClassName
        value: nginx

configMapGenerator:
  - name: cks-terminal-mgmt-config
    behavior: merge
    envs:
      - configmap
